FROM prom/prometheus:latest
COPY prometheus.yml /tmp/
COPY setup.sh /tmp/
USER root
RUN chmod +x /tmp/setup.sh
RUN chmod 777 /tmp/
RUN rm /etc/prometheus/prometheus.yml
ENTRYPOINT [ "/bin/sh", "/tmp/setup.sh" ]


