# my global config
global:
  scrape_interval: 1m # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1m # Evaluate rules every 15 seconds. The default is every 1 minute.
remote_write:
  - url: REMOTE
    sigv4:
      region: eu-west-1
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500
      
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
rule_files:
scrape_configs:
  - job_name: "ZONENAME-prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ZONENAME-Node"
    tls_config:
      insecure_skip_verify: true
    ec2_sd_configs:
      - region: AWSREGION
        profile: AWSROLE
        port: 9100
        filters:
        - name: tag:ECSClusterName
          values:
          - <> 
  
  - job_name: "ZONENAME-CloudWatch"
    tls_config:
      insecure_skip_verify: true
    ec2_sd_configs:
      - region: AWSREGION
        profile: AWSROLE
        port: 9106

  - job_name: "ZONENAME-Docker"
    tls_config:
      insecure_skip_verify: true
    ec2_sd_configs:
      - region: AWSREGION
        profile: AWSROLE
        port: 9200
        filters:
        - name: tag:ECSClusterName
          values:
          - <>
  
  - job_name: "ZONENAME-Postgres"
    tls_config:
      insecure_skip_verify: true
    ec2_sd_configs:
      - region: AWSREGION
        profile: AWSROLE
        port: 9187
        
