name: Docker Push
on:
  workflow_dispatch:
jobs:
 
  Publish-Container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file powercli/Dockerfile --tag nfoley84/powerclicore:latest
    - name: Docker Push
      run: docker push nfoley84/powerclicore
      
  Anchore-Build-Scan:
    runs-on: ubuntu-latest
    needs:  Publish-Container
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nfoley84/powerclicore:latest
    - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
      uses: anchore/scan-action@main
      with:
        image: "nfoley84/powerclicore:latest"
        acs-report-enable: true
    - name: Upload Anchore Scan Report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
        
      
